### ISSUE TITLE
-std=gnu++11 flags is required on XUbuntu 16.04 LTS

### ISSUE THREAD

**Issue by ClaudeMa** [olysonek/grwebsdr#2]
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from globals.h:26,
                 from main.cpp:24:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by ClaudeMa** [comment]
Solved adding
AM_CXXFLAGS = -std=gnu++11
to Makefile.am

**Comment by olysonek** [comment]
Thanks, I guess g++ in Fedora uses C++11 by default. Can you confirm it works even with -std=c++11?

**Comment by ClaudeMa** [comment]
Yes it work
